[project]
main = "Main.kt"
path = "/Users/robin/rust/buildk/example"

[dependencies]
io.ktor.ktor-server-core = "2.3.0"
io.ktor.ktor-server-netty = "2.3.0"
io.ktor.ktor-server-content-negotiation = "2.3.0"
io.ktor.ktor-serialization-jackson = "2.3.0"

[test-dependencies]
org.junit.platform.junit-platform-console-standalone = "1.9.3"

