[project]
main = "Main.kt"
path = "/Users/robin/rust/buildk/example"

[dependencies]
com.google.devtools.ksp.symbol-processing-api = "1.8.21-1.0.11"
com.google.devtools.ksp.symbol-processing-cmdline = "1.8.21-1.0.11"

[test-dependencies]
org.junit.platform.junit-platform-console-standalone = "1.9.3"


