[package]
name = "buildk"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "buildk"
path = "lib.rs"

[workspace]
members = ["crates/*"]

[workspace.dependencies]
cache = { path = "crates/cache" }
config = { path = "crates/config" }
kotlin = { path = "crates/kotlin" }
util = { path = "crates/util" }

anyhow = "1.0"
clap = "4.2.4"
filetime = "0.2.21"
globalenv = "0.4.2"
home = "0.5.4"
lazycell = "1.3.0"
libc = "0.2.141" # get exit codes from OS (SIGKILL, SIGINT etc)
log = "0.4.17"
serde = "1.0.160"
serde_derive = "1.0.160"
serde_json = "1.0.96"
toml = "0.7.3"

[dependencies]
anyhow.workspace = true
config.workspace = true
kotlin.workspace = true
util.workspace = true
