[package]
name = "buildk"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "buildk"
path = "lib.rs"

[workspace]
members = ["crates/*"]

[profile.release]
#lto = true

[workspace.dependencies]
cache = { path = "crates/cache" }
command = { path = "crates/command" }
manifest = { path = "crates/manifest" }
http = { path = "crates/http" }
util = { path = "crates/util" }

anyhow = "1.0.79"
filetime = "0.2.23"
home = "0.5.9"
itertools = "0.12.0"
libc = "0.2.152" # get exit codes from OS (SIGKILL, SIGINT etc)
regex = "1.10.2"

reqwest = { version = "0.11.23", features = ["json", "blocking"]}
#reqwest = { version = "0.11.23", features = ["json", "stream"]}
#tokio = { version = "1.35.1", features = ["full"] }
#futures = "0.3.30"

serde = "1.0.195"
serde_derive = "1.0.195"
serde_json = "1.0.111"
toml = "0.8.8"
toml_edit = "0.21.0"
xml-rs = "0.8.4"

terminal-spinners = "0.3.2"

# graph lib
gryf = { git = "https://github.com/pnevyk/gryf.git" }

[dependencies]
terminal-spinners.workspace = true
anyhow.workspace = true
command.workspace = true
manifest.workspace = true
itertools.workspace = true
util.workspace = true
