[package]
name = "buildk"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "buildk"
path = "lib.rs"

[workspace]
members = ["crates/*"]

[profile.release]
#lto = true

[workspace.dependencies]
cache = { path = "crates/cache" }
command = { path = "crates/command" }
config = { path = "crates/config" }
http = { path = "crates/http" }
util = { path = "crates/util" }

anyhow = "1.0"
filetime = "0.2.21"
home = "0.5.4"
itertools = "0.10.5"
libc = "0.2.141" # get exit codes from OS (SIGKILL, SIGINT etc)
regex = "1.8.1"
reqwest = { version = "0.11.16", features = ["json", "blocking"]}
serde = "1.0.160"
serde_derive = "1.0.160"
serde_json = "1.0.96"
toml = "0.7.3"
toml_edit = "0.19.8"
xml-rs = "0.8.4"

# cross platform terminal lib
#crossterm = "0.27.0"
terminal-spinners = "0.3.2"

# graph lib
gryf = { git = "https://github.com/pnevyk/gryf.git" }

[dependencies]
terminal-spinners.workspace = true
anyhow.workspace = true
#crossterm.workspace = true
command.workspace = true
config.workspace = true
itertools.workspace = true
util.workspace = true
