[package]
name = "buildk"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "buildk"
path = "lib.rs"

[workspace]
members = ["crates/*"]

[profile.release]
lto = true

[workspace.dependencies]
cache = { path = "crates/cache" }
cli = { path = "crates/cli" }
config = { path = "crates/config" }
dependencies = { path = "crates/dependencies" }
kotlin = { path = "crates/kotlin" }
util = { path = "crates/util" }

anyhow = "1.0"
filetime = "0.2.21"
globalenv = "0.4.2"
home = "0.5.4"
lazycell = "1.3.0"
libc = "0.2.141" # get exit codes from OS (SIGKILL, SIGINT etc)
log = "0.4.17"
regex = "1.8.1"
reqwest = { version = "0.11.16", features = ["json", "blocking"]}
serde = "1.0.160"
serde_derive = "1.0.160"
serde_json = "1.0.96"
tempfile = "3.5.0"
toml = "0.7.3"
toml_edit = "0.19.8"
tokio = { version = "1.27.0", features = ["full"] }

[dependencies]
anyhow.workspace = true
tokio.workspace = true

config.workspace = true
dependencies.workspace = true
kotlin.workspace = true
util.workspace = true
