[package]
name = "buildk"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "buildk"
path = "lib.rs"

[workspace]
members = ["crates/*"]

[workspace.dependencies]
# LOCAL
console = { path = "crates/console" }
fs = { path = "crates/fs" }
cmd = { path = "crates/cmd" }

# EXTERNAL
anyhow = "1.0"
toml = "0.7.3"
serde = "1.0.160"
serde_derive = "1.0.160"

[dependencies]
cmd.workspace = true
console.workspace = true
fs.workspace = true

anyhow.workspace = true
