[package]
name = "util"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
filetime.workspace = true
lazycell.workspace = true
libc.workspace = true
log.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
