[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
toml.workspace = true
util.workspace = true

anyhow.workspace = true
home.workspace = true
serde.workspace = true
serde_derive.workspace = true
