[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
util.workspace = true

anyhow.workspace = true
home.workspace = true
regex.workspace = true
serde.workspace = true
serde_derive.workspace = true
toml.workspace = true
toml_edit.workspace = true
