[package]
name = "dependencies"
version = "0.1.0"
edition = "2021"

[dependencies]
config.workspace = true
util.workspace = true

anyhow.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
tempfile.workspace = true
