[package]
name = "dependencies"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
roxmltree.workspace = true 
surf.workspace = true
async-std.workspace = true
gryf.workspace = true

