[package]
name = "process"
version = "0.1.0"
edition = "2021"

[dependencies]
manifest.workspace = true
util.workspace = true
cache.workspace = true

anyhow.workspace = true
filetime.workspace = true
libc.workspace = true

