[package]
name = "manifest"
version = "0.1.0"
edition = "2021"

[dependencies]
util.workspace = true
dependency.workspace = true

async-std.workspace = true
anyhow.workspace = true
home.workspace = true
toml_edit.workspace = true
xml-rs.workspace = true
