[package]
name = "command"
version = "0.1.0"
edition = "2021"

[dependencies]
cache.workspace = true
config.workspace = true
dependencies.workspace = true
util.workspace = true

anyhow.workspace = true
