[package]
name = "command"
version = "0.1.0"
edition = "2021"

[dependencies]
cache.workspace = true
manifest.workspace = true
http.workspace = true
util.workspace = true
gryf.workspace = true
anyhow.workspace = true
