[package]
name = "http"
version = "0.1.0"
edition = "2021"

[dependencies]
manifest.workspace = true

surf.workspace = true
async-std.workspace = true
anyhow.workspace = true
#crossbeam.workspace = true

#reqwest.workspace = true
